### ISSUE TITLE
No option to only log locally

### ISSUE THREAD

**Issue by jmcknight-oiq** [imsweb/mugsy#2]
Skimming over the python code and the config file, I can't see any way to just disable logging to elasticsearch and only log locally. This results in log files full of exceptions rather than useful data.

**Comment by snobear** [comment]
@jmcknight-oiq the `es_logging` option has been added.  You can download the latest rpm (1.0.1) here: https://github.com/imsweb/mugsy/releases/tag/1.0.1

Thanks for the request and let me know if you have any issues.
